language: go

notifications:
  email: false

env:
  global:
    - secure: "HiugtDVkdFQZ6eRno0b3qeimIruPve84NTOSut3olpyOyeFQ42kNq4fN73udbWSBmgQuW6aHw9hmMfB9B6jaqODFSAVvHAe+Bu9900SdI3g2TiTckR918XlftwdWL3GqUZdQgOko+MO9XmmdmaNpPrFEngzPaLUfs+bHM1LIu0Q="
    - PATH=$HOME/gopath/bin:$PATH

before_install:
  - echo yes | sudo apt-add-repository ppa:jjmartinez/sfml-backport
  - sudo sudo apt-get -qq update
  - sudo apt-get install -qq libsfml-dev libsfml-graphics2 libsfml-window2
  - wget http://www.sfml-dev.org/download/csfml/CSFML-2.1-linux-gcc-64bits.tar.bz2
  - tar -xjf CSFML-2.1-linux-gcc-64bits.tar.bz2
  - sudo cp -r CSFML-2.1/* /usr
  - go get golang.org/x/tools/cmd/cover
  - go get golang.org/x/tools/cmd/goimports
  - go get golang.org/x/tools/cmd/vet
  - go get golang.org/x/lint/golint
  - go get github.com/mattn/goveralls

install:
  - go get ./...

before_script:
  - wget https://gist.github.com/mewmew/379014c9a2e6885e238d/raw/goclean.sh
  - chmod +x goclean.sh

script:
  - ./goclean.sh
